### ISSUE TITLE
关于您的博客《C++ 返回局部变量的引用与地址》的提问

### ISSUE THREAD

**Issue by Stpanckr** [zhaozihanzzh/zhaozihanzzh.github.io#1]
在您的博客中，提到示例代码“在 Ubuntu 下用 gcc 9.3.0 编译就不一样了……”。
我复现了在 gcc 9.3.0 环境下出现**段错误**的情况，调试时发现在函数返回`main`时，`rax`寄存器中的值为0。
我的理解是在 gcc 9.3.0 中，针对返回局部变量的引用的情况，安全考虑，返回一个值为`0x0`的地址值。之后在`main`中解析地址`0x0`时，便触发段错误。

您在博客中没有解释 gcc 9.3.0 环境下产生段错误的原因，能否请问我的上述理解是否正确？

感谢您的阅读，期待回复。如有打扰，多多抱歉！

---------------------------

您的博客地址是：https://zhaozihanzzh.github.io/2020/10/24/local-variable-pr/

**Comment by zhaozihanzzh** [comment]
您好，我搜索了一下，看到了一个[答案](https://stackoverflow.com/questions/62203933/c-return-address-of-stack-variable-null)，可能确实是这样的。

**Comment by Stpanckr** [comment]
了解了，十分感谢！
